name: restaurant_mobile
description: Official Ember & Brew Artisan Culinary & Cafe Android App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: 4.14.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app-logo.png

flutter_native_splash:
  color: "#0F0E0C"
  image: assets/images/app-logo.png
  android_12:
    image: assets/images/app-logo.png
    icon_background_color: "#0F0E0C"
